version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/data

volumes:
  sqlite-data:
